apiVersion: v1
kind: Pod
metadata:
  name: rendering-pod
  labels:
    name: rendering-pod
    app: renderscout
spec:
  containers:
    - image: ehsanu/renderscout
      name: rendering-ctr
      ports:
        - containerPort: 3000